export { default as About } from './About'
export { default as Islands } from './game/Islands'
export { default as Home } from './game/Home'
export { default as Authors } from './Authors'
export { default as French } from './French'
export { default as Groups } from './game/Groups'
export { default as Login } from './Login'